### PR TITLE
Feature namespace

### PR DESCRIPTION
**Pull request by eNzyOfficial**
I've namespaced your code and added support for Laravel, pretty sure I've broken your tests, so you will have to run through and fix them. Please could you try and get this pushed out ASAP, we are wanting to use Omise in a new project but do not want to use use the package in it's current state. I don't think you realise how much of a pain in the ass it is having to use an ancient package.

Thanks in advance, looking forward to using the Omise service!

### CODE REVIEW

**Comment by eNzyOfficial** [comment]
Omise is dead now I take it?

**Comment by guzzilar** [comment]
@eNzyOfficial Hi, and sorry that I just saw your pull request here.
Let me have a look through the whole pull request and I'll get back to you soon.

And thank you for following up the namespace issue.
Appreciate.

**Comment by eNzyOfficial** [comment]
Any update on namespacing your code? I've done most of the hard work for you, you just need to handle the tests

**Comment by guzzilar** [comment]
Hi, sorry for accidentally closed your pull request. 
However, a new namespace-introducing pull request has been introduced at #103.
Feel free to review or leave your comment on that pull request.

Thank you for your contribution.

**Pull request closed without merging**
