### PR TITLE
Add namespace to all Omise classes

### PR DESCRIPTION
**Pull request by guzzilar**
> **Note**, need PR #46 to be merged first.

### 1. Objective reason

Continue with PR #46. This PR aimed to add `namespace` back to all of Omise classes.

### 2. Description of change

- Add `PSR-4` spec to composer.json
- New namespaces were introduced to all of Omise classes, the list of namespaces are as follows:

File                                   | Class              | Namespace 
-------------------------------------- | ------------------ | ------------------------
lib/omise/OmiseAccount.php             | OmiseAccount       | Omise\OmiseAccount
lib/omise/OmiseBalance.php             | OmiseBalance       | Omise\OmiseBalance
lib/omise/OmiseCard.php                | OmiseCard          | Omise\OmiseCard
lib/omise/OmiseCardList.php            | OmiseCardList      | Omise\OmiseCardList
lib/omise/OmiseCharge.php              | OmiseCharge        | Omise\OmiseCharge
lib/omise/OmiseCustomer.php            | OmiseCustomer      | Omise\OmiseCustomer
lib/omise/OmiseDispute.php             | OmiseDispute       | Omise\OmiseDispute
lib/omise/OmiseEvent.php               | OmiseEvent         | Omise\OmiseEvent
lib/omise/OmiseRecipient.php           | OmiseRecipient     | Omise\OmiseRecipient
lib/omise/OmiseRefund.php              | OmiseRefund        | Omise\OmiseRefund
lib/omise/OmiseRefundList.php          | OmiseRefundList    | Omise\OmiseRefundList
lib/omise/OmiseTest.php                | OmiseTest          | Omise\OmiseTest
lib/omise/OmiseToken.php               | OmiseToken         | Omise\OmiseToken
lib/omise/OmiseTransaction.php         | OmiseTransaction   | Omise\OmiseTransaction
lib/omise/OmiseTransfer.php            | OmiseTransfer      | Omise\OmiseTransfer
lib/omise/res/OmiseApiResource.php     | OmiseApiResource   | Omise\Res\OmiseApiResource
lib/omise/res/OmiseVaultResource.php   | OmiseVaultResource | Omise\Res\OmiseVaultResource
lib/omise/res/obj/OmiseObject.php      | OmiseObject        | Omise\Res\Obj\OmiseObject
lib/omise/exception/OmiseException.php | OmiseException     | Omise\Exception\OmiseException

**Note**: `lib/omise/exception/OmiseExceptions.php` was changed to `lib/omise/exception/OmiseException.php` to make it corresponding to its class.

### 3. Users affected by the change

No

### 4. Impact of the change

No

### 5. Priority of change

Normal

### 6. Alternate solution

No

### CODE REVIEW

**Comment by guzzilar** [comment]
rebased with #46

**Comment by iwat** [comment]
As the goal is moving toward 3.0 which means **incompatible API changes** in [semantic versioning](http://semver.org). Can we just let go the legacy design and start a new approach? I'm thinking about: namespaces, ditching all static methods (for testability).

**Comment by guzzilar** [comment]
@iwat I see the point, only one concern is, I would like to make it easy for current user who's using version 2.x to easily migrate their implementation code up to `Omise-PHP v3.0.0`.
Then, add `@deprecated` tag first, and remove the legacy afterward. (even in Server says "incompatible API changes", but Im looking for the way that make code simple to migrate).

Do you have any idea on above topic?

**Comment by iwat** [comment]
If thing still works as expected, there is no benefit to migrate the code. Even putting `@deprecated` does not help because it's still docblock and gives no warning at runtime. (PHP has no compile time :D).

I think it's better to keep 2 branches.
- `2-stable` only bug fixes and security fixes.
- `master` new API design, add more features.

Then put a hard deadline to abandon `2-stable`.

**Comment by guzzilar** [comment]
@iwat Sure, keep `2-stable` & `master` is a nice one to go.
My concern is about `more feature` part, to get 1 feature on 3.0.0. User have to re integrate/re test the rest of their code. Thing like that.

Btw, how about wrapper class approach that you were thinking?

**Comment by iwat** [comment]
The only benefit of maintaining wrapper classes is that the user can switch to version 3.0.0 (by simply updating the `composer.json` file) and does nothing. Thing will break again once we remove those wrapper classes.

The down side of wrapper classes is that we need to maintain legacy things in both branches `2-stable` and `master`. And it may force us to design something to support wrapper way. That's my point.

**Comment by guzzilar** [comment]
@iwat 👌 if the new design has lots more pros than con (for legacy support part), then, let's try 👍

**Comment by guzzilar** [comment]
Anyway, this PR should close along with #46.
Are you ok if Im gonna close this PR also? @iwat

**Comment by iwat** [comment]
Sure, let's do this. @guzzilar

**Comment by guzzilar** [comment]
Note, going to close this one now, the new solution for PHP v3.0.0 will be implemented again in the future PR. 😄

**Pull request closed without merging**
