### PR TITLE
Add Search API

### PR DESCRIPTION
**Pull request by bank32**
Add Search API for omise-php

for example

```
// Get request from scope, query and filters
$data = [
    'scope'   => $_GET['scope'],
    'query'   => $_GET['query'],
    'filters' => $_GET['filters'],
];

$querystring = http_build_query($data);
$resources   = OmiseSearch::retrieve($querystring);
```

### CODE REVIEW

**Comment by bank32** [comment]
@guzzilar @nimid could you help me review this PR?, don't hesitate to tell me if something still not good enough.

**Comment by iwat** [comment]
This PR has files that contain illegal characters (?, &) that break Windows user, is it ok to merge changes from `master` to this branch to fix that problem first?

**Comment by bank32** [comment]
@iwat thanks for feedback krub but maybe we should implement this PR in another way.

**Comment by iwat** [comment]
Another way? Is the following use case considered another way?

    public class OmiseChargeTest ... {
      ...
      public function testSearch() {
        $result = OmiseCharge::search('OpenCart');
        $this->assertInstanceOf('OmiseSearchResult', $result);
        foreach ($item in $result['data']) {
          $this->assertInstanceOf('OmiseCharge', $item);
        }
      }
      ...
    }

If so, it's easier to continue from this branch/PR, add `public static function search(...)` method to the supported classes.

**Comment by guzzilar** [comment]
Note, this PR was automatically merged by GitHub, so the status of this PR shows as `Merged` instead of `Closed`. But I already checked at `master` branch, nothing effected.

Also, the new solution for this was introduced at PR #58 
Thanks @bank32 @iwat 👍 👍 👍

**Pull request merged**
