### PR TITLE
Introducing Namespace

### PR DESCRIPTION
**Pull request by guzzilar**
### Objective

Namespace has been used widely all across many PHP projects and frameworks, either open-sourcce or private project. As much as those projects. We also got lots of requests (and complaints) about supporting `namespace` in Omise-PHP library.

This pull request is aiming to provide the support for Namespace.

### Description of Changes
- All resources have been relocated from `lib/omise/*` to `lib/*`

- Removed all those `Omise*` prefix out from its filename and its classname.
i.e.  `lib/omise/OmiseAccount.php` became `lib/Account.php`

- Removed all codes in those legacy classes, and instead, make those classes to inherit from the new class
i.e. 
```php
// lib/omise/OmiseAccount.php
class OmiseAccount extends \Omise\Account { }
```

- At lib/Omise.php file, load those new classes in this file. (in case of manual install)

- Also with the new class structure. Previously you can execute Omise resource by `OmiseCharge::retrieve()`. Now `\Omise\Charge::retrieve()`.

### CODE REVIEW

**Comment by guzzilar** [comment]
Just tested set up on Laravel. It worked fine.
1. At the Laravel's root folder, install Omise-PHP
```
composer require omise/omise-php:dev-add-namespace
```

2. Then, at any controller class, execute
```php
<?php
namespace App\Http\Controllers;

define('OMISE_PUBLIC_KEY', 'pkey_***');
define('OMISE_SECRET_KEY', 'skey_***');

use Omise\Charge;

class PaymentController extends Controller
{
    public function index()
    {
        $charges = Charge::retrieve();
        echo '<pre>';
        print_r($charges);
    }
}
```

**Comment by guzzilar** [comment]
@eNzyOfficial Thanks for mentioning about the environment configuration. 
Will look and find a better way to setup Omise and keys in the next coming PR 👍

**Comment by guzzilar** [comment]
Note: OmiseCapabilities class has been merged to `master` branch after this pull request.
So this pull request still doesn't provide a new namespace for `OmiseCapabilties` (but it should be fine to review right away).

**Comment by eNzyOfficial** [comment]
Any update on when this is going live? Been asking for over a year now

**Pull request merged**
