### PR TITLE
Possibility to get refund list with secret&public keys

### PR DESCRIPTION
**Pull request by sannysoft**

### CODE REVIEW

**Comment by robinclart** [comment]
Hi @sannysoft. Thanks a lot for your PR. Reading your code has brought to my attention that we didn't anticipate this use case–using different keys on the fly–correctly. And so we have decided that we will add those two arguments on every methods that makes a call to our API. If you allow me I'll close this PR and open an issue and let our PHP dev (@guzzilar) take it and do this for you.

**Comment by sannysoft** [comment]
Yeah, that would be great! Thank you.

**Comment by robinclart** [comment]
Here you go. He'll do this ASAP :smile:

**Comment by guzzilar** [comment]
I got it, thanks ! @sannysoft @robinclart

**Comment by sannysoft** [comment]
@robinclart @guzzilar Can you give me an expected release date? We need it ASAP and will make fixes internally if it's not going to be finished this week.

**Comment by robinclart** [comment]
@sannysoft It's nearly done. Just give me a minute to do the review.

**Comment by robinclart** [comment]
@sannysoft We merged into master. If you use composer please wait until below is done. If you just use git then go ahead and pull the change from master. Cheers.

@guzzilar can you bump the minor and make a release. Should be 2.3.2.

**Comment by guzzilar** [comment]
ok, let me do it.

**Comment by sannysoft** [comment]
Thank you, guys!

**Comment by guzzilar** [comment]
Done ! 

Packagist (Composer): https://packagist.org/packages/omise/omise-php#v2.3.2
Github: https://github.com/omise/omise-php/releases/tag/v2.3.2

@sannysoft Thanks for your PR again 😄.

**Pull request closed without merging**
